# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot = {
        initrd = {
            availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
            kernelModules = [ ];

            luks.devices.crypted.device = "/dev/disk/by-label/nixroot";
        };
        kernelModules = [ "kvm-intel" ];
        extraModulePackages = [ ];

        loader.grub.enableCryptodisk = true;
    };

    fileSystems."/" = {
        # device = "/dev/disk/by-label/nixroot";
        device = "/dev/mapper/crypted";
        fsType = "ext4";
    };

    fileSystems."/boot" = {
        device = "/dev/disk/by-label/nixboot";
        fsType = "vfat";
    };

    swapDevices = [ ];

    powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
