#!/bin/sh

# Use bash
export SHELL='bash'

# .bash_profile is executed for login shells,
# .bashrc is executed for interactive non-login shells.
# We want the same behaviour for both, so we source .bashrc from .bash_profile.
# The `.bash_profile` file is sourced by bash when running an interactive session.
# This statement ensures that it is also sourced when running an non-interactive session.
if [[ ! $- == *i* ]]; then
    # echo "This session is not interactive: manually sourcing ~/.bash_profile"
    [ -f ~/.bash_profile ] && . ~/.bash_profile
fi

# source ~/.config/shell/conda
source ~/.config/shell/exputils
