#!/bin/sh

############
# Exputils #
############
# define path to the exputils folder
# PATH_TO_EXPUTILS=$HOME/inria/code/exputils
PATH_TO_EXPUTILS=$HOME/scratch/inria/code/exputils

if [ -d $PATH_TO_EXPUTILS ]; then
    if [ -f "$PATH_TO_EXPUTILS/commands/eu_setup.sh" ] ; then
        . "$PATH_TO_EXPUTILS/commands/eu_setup.sh" "$PATH_TO_EXPUTILS"
    fi
    # set default project for exputils commands
    export EU_DEFAULT_PRJ=rlan
    # activate the default project
    source eu_activate $EU_DEFAULT_PRJ
fi
