#!/bin/sh

# Launch neofetch
# neofetch
pfetch

SHELL_CONFIG_DIR=$HOME/.config/shell

source_file() {
    path_to_source=$SHELL_CONFIG_DIR/$1
    [[ ! -f $path_to_source ]] || source $path_to_source
}

source_file env_variables
source_file inputrc
source_file aliases
source_file ssh
source_file onefetch_hook
source_file conda
source_file exputils
