#!/bin/sh

######################
# SSH agent and keys #
######################
# Gnome keyring daemon
if [ -n "$DESKTOP_SESSION" ];then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK

else
# Else, use the OpenSSH default ssh-agent.

    # 1) Check whether an agent is running. If not, launch one.
    if ! pgrep -u "$USER" ssh-agent > /dev/null; then
        # echo "No ssh agent --> starting one"
        ssh-agent > "/tmp/ssh-agent.env"

        # Reset the environment variable
        SSH_AUTH_SOCK=''
    fi

    # Export the SSH_AUTH_SOCK variable.
    source "/tmp/ssh-agent.env" > /dev/null

    # If no key were added to the agent, look for some keys to add.
    ssh-add -l > /dev/null 2>&1
    if [ $? -ne 0 ] && [[ ! `hostname` =~ "^gpu.*|^node" ]]; then
        ssh-add $(grep -slR "PRIVATE" ~/.ssh/)
    fi
fi
