#!/bin/sh
# ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
# ██ ▄▄ █ ▄▄▀█ ▄▄█▄ ▄█ ▄▄▀█ ▄▄▀████ ████ ▄▄█▀▄▄▀█ ▄▄▀█ ▄▄▄█ ▄▄██
# ██ █▀▀█ ▀▀ █ ▄▄██ ██ ▀▀ █ ██ ████ ████ ▄▄█ ▀▀ █ ▀▀ █ █▄▀█ ▄▄██
# ██ ▀▀▄█▄██▄█▄▄▄██▄██▄██▄█▄██▄████ ▀▀ █▄▄▄█ ████▄██▄█▄▄▄▄█▄▄▄██
# ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
# Website:  glepage.com
# GitHub:   https://github.com/GaetanLepage
# Email:    gaetan.lepage@inria.fr
#
# #--------#
# | zshenv |
# #--------#
# This is where environment variables are sourced.

# Other XDG paths
export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}

# Disable files
export LESSHISTFILE=-

# Fixing Paths
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverrc
export GEM_PATH="$XDG_DATA_HOME/ruby/gems"
export GEM_SPEC_CACHE="$XDG_DATA_HOME/ruby/specs"
export GEM_HOME="$XDG_DATA_HOME/ruby/gems"
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export GOPATH="$XDG_DATA_HOME"/go
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export CARGO_HOME="$XDG_CONFIG_HOME"/cargo

# Zsh
export ZDOTDIR="$XDG_CONFIG_HOME"/shell
export HISTFILE="$ZDOTDIR"/.zsh_history
# Path to your oh-my-zsh installation.
export ZSH=$ZDOTDIR/.oh-my-zsh


# Scaling
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1
export QT_SCREEN_SCALE_FACTORS="1;1;1"
export GDK_SCALE=1
export GDK_DPI_SCALE=1

# Default Apps
export BROWSER="firefox"
export CODEEDITOR="nvim"
export COLORTERM="truecolor"
export EDITOR="nvim"
export FILE="ranger"
export IMAGE="sxiv"
export OPENER="xdg-open"
export PAGER="less"
export READER="zathura"
export STATUSBAR="polybar"
export TERMINAL="kitty"
export VIDEO="mpv"
export VISUAL="nvim"
export WM="bspwm"
# 'bat' as manpager
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MONITOR_TUI_CMD='bpytop'
# 'nvim' as manpager
#export MANPAGER="nvim -c 'set ft=man' -"


export CM_SELECTIONS="clipboard"
export CM_DEBUG=0
export CM_OUTPUT_CLIP=1
export CM_MAX_CLIPS=10

# singularity
# if [[ $(hostname -s) = "alya" ]]; then
#     export SINGULARITY_TMPDIR=$HOME/scratch/tmp
#     export SINGULARITY_CACHEDIR=$HOME/scratch/.cache
# fi

# Path
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/sbin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/scripts:$PATH"
export PATH="$XDG_CONFIG_HOME/nvm/versions/node/v14.4.0/bin:$PATH"
export PATH="$HOME/.local/share/cargo/bin:$PATH"
export PATH="$XDG_CONFIG_HOME/cargo/bin:$PATH"

# Perl
export PATH="/home/gaetan/perl5/bin${PATH:+:${PATH}}"
export PERL5LIB="/home/gaetan/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
export PERL_LOCAL_LIB_ROOT="/home/gaetan/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
export PERL_MB_OPT="--install_base \"/home/gaetan/perl5\""; export PERL_MB_OPT;
export PERL_MM_OPT="INSTALL_BASE=/home/gaetan/perl5"; export PERL_MM_OPT;

# Python PATH
export PYTHONPATH=$PYTHONPATH:/home/gaetan/hevs/implementations/object_detection/models

# Path for lcms2 (kitty dependency)
export PKG_CONFIG_PATH=~/.local/lib/pkgconfig/

# CLion when using a bspwm
export _JAVA_AWT_WM_NONREPARENTING=1
