# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
    config,
    lib,
    pkgs,
    modulesPath,
    ...
}:

{
    # TODO this is tuxedo hardware file
    imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot = {
        initrd = {
            availableKernelModules = [
                "nvme"
                "xhci_pci"
                "ahci"
                "usb_storage"
                "usbhid"
                "sd_mod"
            ];
            kernelModules = [ ];

            luks.devices.crypted.device = "/dev/nvme0n1p2";
        };
        kernelModules = [ "kvm-amd" ];
        extraModulePackages = [ ];
    };

    fileSystems."/" = {
        device = "/dev/disk/by-label/nixroot";
        fsType = "ext4";
    };

    fileSystems."/boot" = {
        device = "/dev/disk/by-label/nixboot";
        fsType = "vfat";
    };

    swapDevices = [
        {
            device = "/dev/disk/by-label/swap";
        }
    ];

    hardware = {
        cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

        # high-resolution display
        video.hidpi.enable = lib.mkDefault true;
    };
}
