#!/bin/sh
# ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
# ██ ▄▄ █ ▄▄▀█ ▄▄█▄ ▄█ ▄▄▀█ ▄▄▀████ ████ ▄▄█▀▄▄▀█ ▄▄▀█ ▄▄▄█ ▄▄██
# ██ █▀▀█ ▀▀ █ ▄▄██ ██ ▀▀ █ ██ ████ ████ ▄▄█ ▀▀ █ ▀▀ █ █▄▀█ ▄▄██
# ██ ▀▀▄█▄██▄█▄▄▄██▄██▄██▄█▄██▄████ ▀▀ █▄▄▄█ ████▄██▄█▄▄▄▄█▄▄▄██
# ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
# Website:  glepage.com
# GitHub:   https://github.com/GaetanLepage
# Email:    gaetan.lepage@inria.fr
#
# #--------------#
# | BSPWM config |
# #--------------#

source $HOME/.config/shell/env_variables

# Reload script (background applications, screen and keyboard management)
source reload

############
# Monitors #
############
bspc monitor $(xrandr | grep -Po ".*(?= connected primary)") -d 1 2 3 4 5 6 7 8 9 10

#########
# Rules #
#########

# Remove all the rules
bspc rule -r "*"

# Floating windows
bspc rule -a Blueman-manager                state=floating
bspc rule -a .blueman-manager-wrapped       state=floating
bspc rule -a Nm-connection-editor           state=floating
bspc rule -a Pavucontrol                    state=floating
bspc rule -a Thunderbird:Calendar:*         state=floating
bspc rule -a update                         state=floating
bspc rule -a Piper                          state=floating
bspc rule -a Solaar                         state=floating
bspc rule -a Steam:Steam:"Steam - News*"    state=floating
bspc rule -a Zathura                        state=tiled

# Workspace assignments
bspc rule -a $BROWSER          desktop=2
bspc rule -a Firefox           desktop=2
bspc rule -a Thunderbird       desktop=4
bspc rule -a Signal            desktop=6
bspc rule -a TelegramDesktop   desktop=6
bspc rule -a Element           desktop=8
bspc rule -a Steam             desktop=8
bspc rule -a Mumble            desktop=8
bspc rule -a Slack             desktop=8
bspc rule -a discord           desktop=8
bspc rule -a "Jitsi Meet"      desktop=8
bspc rule -a nvtop             desktop=10
bspc rule -a $MONITOR_TUI_CMD  desktop=10

# Automatically set certain worskpaces' layout
bspc desktop 2 -l monocle
bspc desktop 4 -l monocle
bspc desktop 7 -l monocle
bspc desktop 8 -l monocle

# Add custom rules for Spotify and zotero
bspc config external_rules_command "$XDG_CONFIG_HOME/bspwm/custom_rules.sh"


###################
# Global settings #
###################
bspc config border_width                2
bspc config window_gap                  0

bspc config top_padding                 0
bspc config bottom_padding              30
bspc config left_padding                0
bspc config right_padding               0

bspc config single_monocle              true
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config pointer_follows_focus       false

bspc config merge_overlapping_monitors  true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

bspc config ignore_ewmh_focus           true

bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner

##########
# Colors #
##########
bspc config normal_border_color         "#282828"
bspc config active_border_color         "#282828"
bspc config focused_border_color        "#ebdbb2"
bspc config presel_feedback_color       "#ebdbb2"
bspc config urgent_border_color         "#cc241d"


#############
# Autostart #
#############

is_it_running() {
    # If the program is not installed, no need to go further
    type     $1 > /dev/null 2>&1    || { echo "$1 is not installed on the system" && return 1; }

    # Is the program is already running, no need to launch it
    pgrep -f $1 > /dev/null 2>&1    && { echo "$1 is already running"             && return 2; }

    echo "$1 was not running."
}

run_if_not_running() {

    is_it_running $1 || return 1

    # Run the program in the background
    echo "Running $1 in the background (command: '$@')"
    $@ &
}

run_in_terminal() {
    is_it_running $1 || return 1

    # Run the program in a new terminal
    $TERMINAL --class $1 $@ &
}


#############
# Autostart #
#############

# Update lock screen wallpaper size
betterlockscreen -u ~/.config/wallpaper.jpg

# Go to desktop 1 to run terminal
is_it_running $TERMINAL && bspc desktop -f 1 && $TERMINAL

run_if_not_running $BROWSER

run_in_terminal nvtop
run_in_terminal $MONITOR_TUI_CMD

run_if_not_running thunderbird
run_if_not_running signal-desktop
