#!/bin/sh
# ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
# ██ ▄▄ █ ▄▄▀█ ▄▄█▄ ▄█ ▄▄▀█ ▄▄▀████ ████ ▄▄█▀▄▄▀█ ▄▄▀█ ▄▄▄█ ▄▄██
# ██ █▀▀█ ▀▀ █ ▄▄██ ██ ▀▀ █ ██ ████ ████ ▄▄█ ▀▀ █ ▀▀ █ █▄▀█ ▄▄██
# ██ ▀▀▄█▄██▄█▄▄▄██▄██▄██▄█▄██▄████ ▀▀ █▄▄▄█ ████▄██▄█▄▄▄▄█▄▄▄██
# ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
# Website:  glepage.com
# GitHub:   https://github.com/GaetanLepage
# Email:    gaetan.lepage@inria.fr
#
# #--------------#
# | BSPWM config |
# #--------------#

source ~/.zshenv

############
# Monitors #
############
HOSTNAME=$(hostname)
case $HOSTNAME in
    # Desktop PC
    gaetan-desktop-arch)
        #bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 10
        bspc monitor DP-0 -d 1 2 3 4 5 7
        bspc monitor HDMI-0 -d 6 8 9 10
        ;;
    # Laptop
    gaetan-xps)
        bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
        ;;
    alya)
        bspc monitor DP-4 -d 1 2 3 4 5 7
        bspc monitor DP-1 -d 6 8 9 10
        ;;
esac

#########
# Rules #
#########

# Remove all the rules
bspc rule -r "*"

# Floating windows
bspc rule -a Blueman-manager                state=floating
bspc rule -a Pavucontrol 	                state=floating
bspc rule -a Thunderbird:Calendar:*         state=floating
bspc rule -a update                         state=floating
bspc rule -a Piper                          state=floating
bspc rule -a Solaar                         state=floating
bspc rule -a Steam:Steam:"Steam - News*"    state=floating
bspc rule -a Zathura                        state=tiled

# Workspace assignments
bspc rule -a firefox           desktop=2
bspc rule -a Thunderbird       desktop=4
bspc rule -a Signal            desktop=6
bspc rule -a TelegramDesktop   desktop=6
bspc rule -a Element           desktop=8
bspc rule -a Steam             desktop=8
bspc rule -a Mumble            desktop=8
bspc rule -a discord           desktop=8
bspc rule -a "Jitsi Meet"      desktop=8
bspc rule -a nvtop             desktop=10
bspc rule -a gotop             desktop=10

# Automatically set certain worskpaces' layout
bspc desktop 2 -l monocle
bspc desktop 4 -l monocle
bspc desktop 5 -l monocle

# Add custom rules for Spotify and zotero
bspc config external_rules_command "$XDG_CONFIG_HOME/bspwm/custom_rules.sh"


###################
# Global settings #
###################
bspc config border_radius               8
bspc config border_width                2
bspc config window_gap                  0

bspc config top_padding                 0
bspc config bottom_padding              40
bspc config left_padding                0
bspc config right_padding               0

bspc config single_monocle              true
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config pointer_follows_focus       true

bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  true
bspc config remove_unplugged_monitors   true

bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner


##########
# Colors #
##########
# Get colors from Xresources
bspc config normal_border_color		"$(xgetres bspwm.color0)"
bspc config active_border_color	    "$(xgetres bspwm.color0)"
bspc config focused_border_color	"$(xgetres bspwm.color15)"
bspc config presel_feedback_color	"$(xgetres bspwm.color15)"
bspc config urgent_border_color 	"$(xgetres bspwm.color1)"


#############
# Autostart #
#############

# Reload script (background applications, screen and keyboard management)
reload


run_if_not_running() {
    # If the program is not installed, no need to go further
    type $1 > /dev/null 2>&1   || { echo "$1 is not installed on the system" && return; }
    # Is the program is already running, no need to launch it
    pidof $1  > /dev/null 2>&1 && { echo "$1 is already running"             && return; }

    # Run the program in the background
    echo "Running $1 in the background (command: '$@')"
    $@ &
}

# Go to desktop 1 to run terminal
bspc desktop -f 1 && run_if_not_running $TERMINAL
run_if_not_running $BROWSER
run_if_not_running zotero

case $HOSTNAME in
    alya)
        export $(dbus-launch)
        pidof thunderbird || gtk-launch org.mozilla.Thunderbird

        pidof signal-desktop || gtk-launch org.signal.Signal.desktop
        pidof telegram-desktop || gtk-launch org.telegram.desktop.desktop
        pidof element-desktop || gtk-launch im.riot.Riot.desktop

        # TODO change
        pidof slack || gtk-launch gtk-launch com.slack.Slack.desktop

        flameshot &
        ;;

    *)
        run_if_not_running thunderbird
        run_if_not_running signal-desktop
        run_if_not_running telegram-desktop
        #run_if_not_running spotify
        ;;
esac

type nvtop > /dev/null 2>&1 && { pidof nvtop > /dev/null 2>&1 || $TERMINAL --class nvtop nvtop & }
type gotop > /dev/null 2>&1 && { pidof gotop > /dev/null 2>&1 || $TERMINAL --class gotop gotop & }
