#!/bin/sh
# ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
# ██ ▄▄ █ ▄▄▀█ ▄▄█▄ ▄█ ▄▄▀█ ▄▄▀████ ████ ▄▄█▀▄▄▀█ ▄▄▀█ ▄▄▄█ ▄▄██
# ██ █▀▀█ ▀▀ █ ▄▄██ ██ ▀▀ █ ██ ████ ████ ▄▄█ ▀▀ █ ▀▀ █ █▄▀█ ▄▄██
# ██ ▀▀▄█▄██▄█▄▄▄██▄██▄██▄█▄██▄████ ▀▀ █▄▄▄█ ████▄██▄█▄▄▄▄█▄▄▄██
# ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
# Website:  glepage.com
# GitHub:   https://github.com/GaetanLepage
# Email:    gaetan.lepage@inria.fr
#
# #----------#
# | xprofile |
# #----------#
#
# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# executes scripts before the WM is launched
command -v autorandr && autorandr -c

# Start the Gnome keyring daemon.
if [ command -v gnome-keyring-daemon 2>&1 > /dev/null ]; then
    eval $(gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
    # export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
fi

dbus-update-activation-environment --systemd DISPLAY

# Load Xresources
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources

dunst &			                    # dunst for notifications
udiskie &                           # automatically mounts disks
