-- Packer
require 'plugins.packer'

-- Plugins configuration
require 'plugins.barbar'
require 'plugins.colorizer'
require 'plugins.comment'
require 'plugins.compe'
require 'plugins.floaterm'
require 'plugins.fugitive'
require 'plugins.lspsaga'
require 'plugins.lualine'
require 'plugins.markdown-preview'
require 'plugins.nvim-autopairs'
require 'plugins.nvimtree'
require 'plugins.rnvimr'
require 'plugins.simpylfold'
require 'plugins.startify'
require 'plugins.tagbar'
require 'plugins.telescope'
require 'plugins.treesitter'
require 'plugins.trouble'
require 'plugins.vimtex'
