-- Packer
require 'plugins.packer'

-- Plugins configuration
require 'plugins.barbar'
require 'plugins.colorizer'
require 'plugins.comment'
require 'plugins.compe'
-- require 'plugins.floaterm'
require 'plugins.fugitive'
require 'plugins.galaxyline'
-- require 'plugins.gitsigns'
-- require 'plugins.indentline'
require 'plugins.markdown-preview'
-- require 'plugins.nv-neomake'
require 'plugins.nvim-autopairs'
require 'plugins.nvimtree'
require 'plugins.rnvimr'
require 'plugins.startify'
require 'plugins.simpylfold'
require 'plugins.tagbar'
require 'plugins.treesitter'
require 'plugins.telescope'
require 'plugins.trouble'
require 'plugins.vimtex'
-- require 'plugins.vista'
-- require 'plugins.floaterm'
-- require 'plugins.lspkind'
