#!/bin/sh

if ! [ `hostname` = "tuxedo" ]; then
    echo "Not on tuxedo --> exiting"
    exit 1
fi

DRY_RUN=''
if [ "$1" = "-d" ]; then
    DRY_RUN='--dry-run'
fi


dest_path=/zfspool/gaetan/backup/home

rsync -zravutP $HOME/ server:$dest_path \
    --human-readable \
    --delete \
    --delete-excluded \
    --exclude "__pycache__/" \
    --exclude ".cache/" \
    --exclude ".config/cargo/" \
    --exclude ".config/discord/" \
    --exclude ".config/Discord/" \
    --exclude ".config/Jitsi Meet/" \
    --exclude ".config/Microsoft/" \
    --exclude ".config/Slack/" \
    --exclude "**/.julia/" \
    --exclude ".mozilla/firefox/gaetan/storage/default/https+++app.slack.com/" \
    --exclude ".local/share/lbry/" \
    --exclude ".local/share/nvim/" \
    --exclude ".local/share/R/" \
    --exclude ".local/share/Steam/" \
    --exclude ".local/share/TelegramDesktop/" \
    --exclude ".mypy_cache/" \
    --exclude ".npm/" \
    --exclude "node_modules/" \
    --exclude "server/" \
    --exclude "venv/" \
    $DRY_RUN
