#!/bin/sh

if ! [ `hostname` = "tuxedo" ]; then
    echo "Not on tuxedo --> exiting"
    exit 1
fi

dest_path=/zfspool/gaetan/backup/home

rsync -zravut $HOME/ server:$dest_path \
    --delete \
    --delete-excluded \
    --exclude "__pycache__/" \
    --exclude ".cache/" \
    --exclude ".config/Discord/" \
    --exclude ".mozilla/firefox/gaetan/storage/default/https+++app.slack.com/" \
    --exclude ".local/share/nvim/" \
    --exclude ".local/share/R/" \
    --exclude ".local/share/TelegramDesktop/" \
    --exclude ".mypy_cache/" \
    --exclude ".npm/" \
    --exclude "node_modules/" \
    --exclude "server/" \
    --exclude "venv/" \
    # --dry-run
