#!/bin/sh

dest_path=/zfspool/gaetan/backup/home

rsync -zravut $HOME/ server:$dest_path \
    --delete \
    --delete-excluded \
    --exclude ".cache/" \
    --exclude ".local/share/R/" \
    --exclude ".local/share/nvim/" \
    --exclude ".mypy_cache/" \
    --exclude ".npm/" \
    --exclude "node_modules/" \
    --exclude "__pycache__/" \
    --exclude "venv/" \
    # --dry-run
