#!/bin/sh

case $1 in
    h)
        bspc node -z left -20 0 || bspc node -z right -20 0
        ;;
    j)
        bspc node -z bottom 0 20 || bspc node -z top 0 20
        ;;
    k)
        bspc node -z top 0 -20 || bspc node -z bottom 0 -20
        ;;
    l)
        bspc node -z right 20 0 || bspc node -z left 20 0
        ;;
esac
