#!/bin/bash
# ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
# ██ ▄▄ █ ▄▄▀█ ▄▄█▄ ▄█ ▄▄▀█ ▄▄▀████ ████ ▄▄█▀▄▄▀█ ▄▄▀█ ▄▄▄█ ▄▄██
# ██ █▀▀█ ▀▀ █ ▄▄██ ██ ▀▀ █ ██ ████ ████ ▄▄█ ▀▀ █ ▀▀ █ █▄▀█ ▄▄██
# ██ ▀▀▄█▄██▄█▄▄▄██▄██▄██▄█▄██▄████ ▀▀ █▄▄▄█ ████▄██▄█▄▄▄▄█▄▄▄██
# ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
# Website:  glepage.com
# GitHub:   https://github.com/GaetanLepage
# Email:    gaetan.lepage@inria.fr
#
# #-------------#
# | lock script |
# #-------------#
# Locks the computer screen.
# Pauses notifications while screen is locked.

# Pause notifications
notifs_are_already_off=$(dunstctl is-paused)
# notifs_are_already_off='false'
# echo "Notifs were already off: $notifs_are_already_off"
# if [ $notifs_are_already_off = 'false' ]; then
#     echo -e "\nBlock notifications"
#     dunstctl set-paused true && echo "succesfully blocked ntofications"
# fi

# Pause any playing video / song
echo -e "\nPause any playing video/song"
playerctl pause

# Pause spotify
echo -e "\nPause spotify"
playerctl -p spotify pause

# Lock the screen
echo -e "\nLock screen"
# betterlockscreen -l
multilockscreen -l

# Resume notifications
# if [ $notifs_are_already_off = 'false' ]; then
#     echo -e "\nResume notifications"
#     dunstctl set-paused false
# fi
