#!/bin/sh

if [ "$1" = 'stop' ]; then
    killall mpv
    notify-send "Stopping Lofi Girl stream"

elif ! pgrep mpv > /dev/null ; then
    notify-send "Starting Lofi Girl stream"
    mpv "https://www.youtube.com/watch?v=5qap5aO4i9A" --no-video
fi
