#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

#for m in $(polybar --list-monitors | cut -d":" -f1); do
	#WIRELESS=$(ls /sys/class/net/ | grep ^wl | awk 'NR==1{print $1}') MONITOR=$m polybar --reload -l info mainbar-i3 &
#done
#for i in $(polybar -m | awk -F: '{print $1}'); do
#for i in IFS=\n $(polybar -m); do
#IFS='\n'
#for i in $(polybar -m); do
polybar -m | while IFS= read -r line;do

    # Get the name of the monitor
    echo $line
    MONITOR=$(echo $line | cut -d: -f1)
    echo "Monitor = "$MONITOR

    # Detect if this monitor is the primary one
    IS_PRIMARY=$(echo $line | grep -Po '(?<=\().*(?=\))')
    if [[ $IS_PRIMARY ]] ; then export TRAY_POS=right; else TRAY_POS=none ; fi
    echo $TRAY_POSE

    # Launch the bar
    TRAY_POS=$TRAY_POS MONITOR=$MONITOR polybar mainbar-i3 -r &
done

echo "Bars launched..."
