#!/bin/sh
# ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
# ██ ▄▄ █ ▄▄▀█ ▄▄█▄ ▄█ ▄▄▀█ ▄▄▀████ ████ ▄▄█▀▄▄▀█ ▄▄▀█ ▄▄▄█ ▄▄██
# ██ █▀▀█ ▀▀ █ ▄▄██ ██ ▀▀ █ ██ ████ ████ ▄▄█ ▀▀ █ ▀▀ █ █▄▀█ ▄▄██
# ██ ▀▀▄█▄██▄█▄▄▄██▄██▄██▄█▄██▄████ ▀▀ █▄▄▄█ ████▄██▄█▄▄▄▄█▄▄▄██
# ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
# Website:  glepage.com
# GitHub:   https://github.com/GaetanLepage
# Email:    gaetan.lepage@inria.fr
#
# #---------------#
# | reload script |
# #---------------#


#############
# Functions #
#############

run_in_bg() {
    echo -e "> running $1 in the background (command: '$@')\n"
    $@ &
}

kill_and_run() {
    echo "killing all instances of $1"
    # Kill all the existing instances
    killall $1 >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo "> killed all instances of $1"

        # Wait for the instances to properly shutdown
        #sleep 0.5s
    else
        echo "> $1 was not running. Starting it right now !"
    fi

    # Run the program in the background
    run_in_bg $@
}


is_it_running() {
    # If the program is not installed, no need to go further
    type $1 > /dev/null 2>&1   || { echo "$1 is not installed on the system" && return 1; }
    # Is the program is already running, no need to launch it
    pidof $1  > /dev/null 2>&1 && { echo "$1 is already running"             && return 2; }

    echo "$1 was not running."
}

run_if_not_running() {

    is_it_running $1 || return 1

    # Run the program in the background
    echo "Running $1 in the background (command: '$@')"
    $@ &
}


##########
# Screen #
##########

# Monitor setup
autorandr -c

# Set the desktop wallpaper
run_in_bg setbg

# Run picom
run_if_not_running picom -b --experimental-backends

MONITOR_RESOLUTION=$(xrandr | grep -Po "(?<=connected primary ).+?(?=\+)")
case $MONITOR_RESOLUTION in
    1920x1080|1920x1200)
        export POLYBAR_HEIGHT=30
        export POLYBAR_FONT_0_SIZE=10
        export POLYBAR_FONT_1_SIZE=6
        break
        ;;
    *)
        export POLYBAR_HEIGHT=40
        export POLYBAR_FONT_0_SIZE=12
        export POLYBAR_FONT_1_SIZE=8
        ;;
esac
export POLYBAR_FONT_0='Ubuntu Nerd Font:style=Book:size='${POLYBAR_FONT_0_SIZE}';1'
export POLYBAR_FONT_1='NotoSans Mono:size='${POLYBAR_FONT_1_SIZE}';0'


############
# Keyboard #
############

# Lock the numpad
run_if_not_running numlockx

# Keyboard remaps
run_in_bg remaps

# Run the keyboard daemon (if we are on BSPWM)
[[ $WM == "bspwm" ]] && kill_and_run sxhkd

# Logitech keyboard backlight profile
type g610-led && run_if_not_running g610-led -a ff


###########
# Applets #
###########
# Run bluetooth applet only if it is not alya.
[[ $(hostname -s) = "alya" ]] || run_if_not_running blueman-applet


[[ $(hostname -s) = "alya" ]] && ssh -CnfND 8080 server

run_if_not_running nm-applet
run_if_not_running nextcloud


########
# Misc #
########

# Load Xresources
xrdb ~/.Xresources

# Launch polybar
run_in_bg polybar_launch
