#!/bin/bash

# Auto
echo "SCREEN"
screens $$ echo "SCREEN done"&

echo "REMPAPS"
remaps && echo "REMAPS done"&

sleep 3

echo "WALLPAPER"
setbg && echo "WALLPAPER done"&

echo "POLYBAR"
polybar_launch && echo "POLYBAR done" &
