#!/bin/sh

# This script is called on startup to remap keys.
# Increase key speed via a rate change
xset r rate 300 50

# Set french keyboard layout
setxkbmap -layout fr

# Switch escape and caps lock
setxkbmap -option caps:swapescape
