#!/bin/sh

HOSTNAME=$(hostname)
echo "detected system : "$HOSTNAME


disable_output () {
    xrandr | grep "${1} connected" && xrandr --output $1 --off
}

disable_all () {
    disable_output eDP-1
    disable_output DP-1
    disable_output DP-1-1
    disable_output DP-1-3
    disable_output DP-2
    disable_output DP-2-2
    disable_output DP-2-3
    disable_output VIRTUAL-1
}

dual_screen () {
    xrandr --output $BENQ --mode 1920x1080 --pos 0x0 --rotate normal --output $S144 --mode 1920x1080 --rate 144 --primary --pos 1920x0 --rotate normal
}

is_connected() {
    # $1 : name of an output

    # Check if the display is connected or not
    STATE=$(xrandr | grep -oP '(?<=\b'$1'\s)\w+')

    echo "$1 is ${STATE}"

    if [ "$STATE" == "connected" ]
    then
        return 0
    elif [ "$STATE" == "disconnected" ]
    then
        return 1
    fi

    return 1

}


# Start by disabling all outputs
disable_all


case $HOSTNAME in
    # Desktop PC
    gaetan-desktop-arch)

        S144="DP-0"
        BENQ="HDMI-0"

        # if both screen are connected
        if is_connected "$S144" && is_connected "$BENQ";
        then
            echo "HOSTNAME = ${HOSTNAME} - MODE = dual screen"
            dual_screen

        # If only the main 144Hz screen is connected
        elif is_connected "$S144";
        then
            echo "HOSTNAME = ${HOSTNAME} - only 144"
            xrandr --output $S144 --mode 1920x1080 --rate 144 --primary --pos 1920x0 --rotate normal
        fi
        ;;

    # Laptop
    gaetan-xps)
        LAPTOP_SCREEN="eDP-1"
        EXTERNAL="DP-1"
        S144="DP-1-2"
        BENQ="DP-2-1"

        # Dual screen (TB3 dock)
        if is_connected "$S144" && is_connected "$BENQ";
        then
            echo "Dual screen"
            dual_screen

            # Turn wifi off
            nmcli radio wifi off

        # External only
        elif is_connected "$EXTERNAL";
        then
            #echo "Single external screen"
            #xrandr --output "$EXTERNAL" --mode 1920x1080 --pos 0x0 --rotate normal
            mons -e right

        # Laptop only
        elif is_connected "$LAPTOP_SCREEN";
        then
            echo "laptop screen only"
            xrandr --output "$LAPTOP_SCREEN" --mode 1920x1080 --pos 0x0 --rotate normal

            # start wifi
            nmcli radio wifi on

        fi

        ;;

    # Inria
    alya)

        xrandr --output USB-C-0 --off
        xrandr --output DP-0 --off
        xrandr --output DP-3 --off
        xrandr --output DP-2 --off
        xrandr --output DP-5 --off
        xrandr --output DP-1 --mode 1920x1200 --pos 0x0 --rotate normal
        xrandr --output DP-4 --primary --mode 2560x1440 --pos 1920x0 --rotate normal

        ;;
esac
