#!/bin/bash

disable_output () {
    xrandr | grep "${1} connected" && xrandr --output $1 --off
}

disable_all () {
    disable_output eDP-1
    disable_output DP-1
    disable_output DP-1-1
    disable_output DP-1-3
    disable_output DP-2
    disable_output DP-2-2
    disable_output DP-2-3
    disable_output VIRTUAL-1
}

dual_screen () {
    #xrandr --output $BENQ --mode 1920x1080 --pos 0x0 --rotate normal --output $S144 --mode 1920x1080 --rate 144 --primary --pos 1920x0 --rotate normal
    xrandr --output $S144 --mode 1920x1080 --rate 144 --pos 0x180 --rotate normal
    xrandr --output $INRIA --primary --mode 2560x1440 --pos 1920x0 --rotate normal
    xrandr --output $LAPTOP_SCREEN --off
    #xrandr --output $BENQ --off --output $S144 --primary --mode 1920x1080 --rate 144 --pos 0x0 --rotate normal

    bspc monitor $INRIA -d 1 2 3 4 5 7
    bspc monitor $S144 -d 6 8 9 10
}

toggle_csgo () {

    echo "TOGGLING CSGO MODE"

    output=$(nvidia-settings --query CurrentMetaMode)

    if echo ${output} | grep -q "1024x768"
    then
        echo "exiting CSGO mode"
        nvidia-settings --assign CurrentMetaMode="DP-0: 1920x1080 { ViewPortIn=1920x1080, ViewPortOut=1920x1080 RefreshRate=144 }"
        xrandr --output DP-0 --mode 1920x1080 --rate 144 --primary

    else
        echo "entering CSGO mode"
        nvidia-settings --assign CurrentMetaMode="DP-0: 1024x768 { ViewPortIn=1024x768, ViewPortOut=804x768+110+0 RefreshRate=144 }"
    fi
}


is_connected() {
    # $1 : name of an output

    # Check if the display is connected or not
    STATE=$(xrandr | grep -oP '(?<=\b'$1'\s)\w+')

    case $STATE in
        "connected")
            echo "$1 is connected."
            return 0
            ;;
        "disconnected")
            echo "$1 is disconnected."
            return 1
            ;;
        "")
            echo "$1 is not available on this machine."
            return 1
            ;;
        *)
            return 1
    esac
}


auto_config() {
    HOSTNAME=$(hostname)
    echo "detected system : "$HOSTNAME

    case $HOSTNAME in
        # Desktop PC
        gaetan-desktop-arch)

            S144="HDMI-0"
            INRIA="DP-0"

            # if both screen are connected
            if is_connected "$S144" && is_connected "$INRIA";
            then
                echo "HOSTNAME = ${HOSTNAME} - MODE = dual screen"
                #xrandr --output HDMI-0 --off --output DP-0 --mode 1920x1080 --rate 144 --primary
                dual_screen

            # If only the main 144Hz screen is connected
            elif is_connected "$S144";
            then
                echo "HOSTNAME = ${HOSTNAME} - only 144"
                xrandr --output $S144 --mode 1920x1080 --rate 144 --primary --pos 1920x0 --rotate normal
            fi
            ;;

        # Laptop
        gaetan-xps)
            LAPTOP_SCREEN="eDP-1"
            EXTERNAL="DP-1"
            S144="DP-2-1"
            INRIA="DP-1-2"

            # Dual screen (TB3 dock)
            if is_connected "$S144" && is_connected "$INRIA";
            then
                echo "Dual screen"
                dual_screen

                # Turn wifi off
                nmcli radio wifi off

            # External only
            elif is_connected "$EXTERNAL";
            then
                echo "Single external screen"
                xrandr --output "$LAPTOP_SCREEN" --off
                xrandr --output "$EXTERNAL" --mode 1920x1080 --pos 0x0 --rotate normal --primary
                bspc monitor $EXTERNAL -d 1 2 3 4 5 6 7 8 9 10

            # Laptop only
            elif is_connected "$LAPTOP_SCREEN";
            then
                echo "laptop screen only"
                xrandr --output "$LAPTOP_SCREEN" --mode 1920x1080 --pos 0x0 --rotate normal
                bspc monitor $LAPTOP_SCREEN -d 1 2 3 4 5 6 7 8 9 10

                # start wifi
                nmcli radio wifi on
            fi

            ;;

        # Inria
        alya)
            #xrandr --output DP-4 --mode 1920x1200 --pos 0x0 --rotate normal --output USB-C-0 --primary --mode 1920x1080 --pos 1920x0 --rotate normal
            xrandr --output DP-1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-4 --primary --mode 1920x1200 --pos 1920x0 --rotate normal
            ;;
    esac
}


# Start by disabling all outputs
#disable_all

case $1 in
    "toggle_csgo")

        toggle_csgo
        exit 0
        ;;
    "")
        auto_config
        exit 0
        ;;
esac

