#!/bin/bash

echo "Updating system packages"
distro=$(cat /etc/os-release | grep -oP '(?<=^ID=).*')
echo "Detected distribution: $distro"

# Ubuntu / Debian
if [[ $distro =~ ubuntu|debian ]]; then
    sudo apt-get update
    sudo apt-get upgrade

elif [ $distro == 'arch' ]; then

    if which paru >/dev/null 2>&1; then
        echo 'Update using paru'
        prog='paru'

    elif which yay >/dev/null 2>&1; then
        echo 'Update using yay'
        prog='yay'

    else
        echo 'Update using pacman'
        prog='sudo pacman'
    fi

    $prog -Syu --noconfirm --needed
fi
