#!/usr/bin/env bash

# Stop execution if an error occurs
set -e

# echo "Updating system packages"
distro=$(cat /etc/os-release | grep -oP '(?<=^ID=).*')
# echo "Detected distribution: $distro"

# Ubuntu / Debian
if [[ $distro =~ ubuntu|debian ]]; then
    sudo apt-get update
    sudo apt-get upgrade

elif [ $distro == 'arch' ]; then

    if which paru >/dev/null 2>&1; then
        # echo 'Update using paru'
        prog='paru'

    elif which yay >/dev/null 2>&1; then
        # echo 'Update using yay'
        prog='yay'

    else
        # echo 'Update using pacman'
        prog='sudo pacman'
    fi

    $prog -Syu --noconfirm

elif [ $distro == 'nixos' ]; then
    # Path to the folder containing `flake.nix`
    nix_dir=$HOME/.dotfiles

    # Update the flake's inputs
    nix flake update $nix_dir -L

    # Reload the system configuration
    sudo nixos-rebuild switch --flake $nix_dir -v

    # Remove old generations
    sudo nix-collect-garbage --delete-older-than 2d

    # Clean the store (garbage collection)
    nix-store --gc
fi
