#!/bin/sh
# ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
# ██ ▄▄ █ ▄▄▀█ ▄▄█▄ ▄█ ▄▄▀█ ▄▄▀████ ████ ▄▄█▀▄▄▀█ ▄▄▀█ ▄▄▄█ ▄▄██
# ██ █▀▀█ ▀▀ █ ▄▄██ ██ ▀▀ █ ██ ████ ████ ▄▄█ ▀▀ █ ▀▀ █ █▄▀█ ▄▄██
# ██ ▀▀▄█▄██▄█▄▄▄██▄██▄██▄█▄██▄████ ▀▀ █▄▄▄█ ████▄██▄█▄▄▄▄█▄▄▄██
# ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
# website:  glepage.com
# github:   https://github.com/gaetanlepage
# email:    gaetan.lepage@inria.fr
#
# #---------------#
# | volume script |
# #---------------#


update_sink() {
    SINK=$(pactl list short sinks | grep RUNNING | cut -f1)

    [ -z "$SINK" ] && SINK=$(pactl list short sinks | cut -f1 | tail -n 1)
    [ -z "$SINK" ] && SINK=0

    #echo "Detected sink: $SINK"
}

increase_volume() {
    STEP=$1
    pactl set-sink-volume "$SINK" +"$STEP"%
}

decrease_volume() {
    STEP=$1
    pactl set-sink-volume "$SINK" -"$STEP"%
}

update_sink

case $1 in
    up|down)
        provided_step=$2
        STEP=${provided_step:=10}

        case $1 in
            up)
                # Unmute first
                pactl set-sink-mute ${SINK} 0

                increase_volume $STEP
            ;;
            down)
                # Unmute first
                pactl set-sink-mute ${SINK} 0

                decrease_volume $STEP
            ;;
            *)
        esac
        ;;
    mute_toggle)
        pactl set-sink-mute ${SINK} toggle
    ;;
    *)
esac
