#!/bin/sh
# ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
# ██ ▄▄ █ ▄▄▀█ ▄▄█▄ ▄█ ▄▄▀█ ▄▄▀████ ████ ▄▄█▀▄▄▀█ ▄▄▀█ ▄▄▄█ ▄▄██
# ██ █▀▀█ ▀▀ █ ▄▄██ ██ ▀▀ █ ██ ████ ████ ▄▄█ ▀▀ █ ▀▀ █ █▄▀█ ▄▄██
# ██ ▀▀▄█▄██▄█▄▄▄██▄██▄██▄█▄██▄████ ▀▀ █▄▄▄█ ████▄██▄█▄▄▄▄█▄▄▄██
# ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
# website:  glepage.com
# github:   https://github.com/gaetanlepage
# email:    gaetan.lepage@inria.fr
#
# #---------------#
# | volume script |
# #---------------#


update_sink() {
    SINK=$(pactl list short sinks | grep RUNNING | cut -f1)

    [ -z "$SINK" ] && SINK=$(pactl list short sinks | cut -f1 | tail -n 1)
    [ -z "$SINK" ] && SINK=0

    #echo "Detected sink: $SINK"
}

increase_volume() {
    STEP=$1
    pactl set-sink-volume "$SINK" +"$STEP"%
}

decrease_volume() {
    STEP=$1
    pactl set-sink-volume "$SINK" -"$STEP"%
}

mute() {
    pactl set-sink-mute ${SINK} toggle
}

update_sink

case $1 in
    up|down)
        if [ -z "$2" ]
        then
            # No step was provided: using the default step
            STEP=10
        else
            # Using the given step
            STEP=$2
        fi

        case $1 in
            up)
                increase_volume $STEP
            ;;
            down)
                decrease_volume $STEP
            ;;
            *)
        esac
        ;;
    mute)
        mute
    ;;
    *)
esac

