#!/bin/sh

play_stream() {
    if pgrep mpv > /dev/null; then
        dunstify "MPV is already running.\nRun '$0 stop'."
    fi

    dunstify "Starting '$stream_name' stream"
    mpv --no-video "https://www.youtube.com/watch?v=$1"
}


stream_name=$1

case $stream_name in
    stop)
        killall mpv
        dunstify "Stopping stream"
        ;;
    lofi)
        play_stream "jfKfPfyJRdk"
        ;;
    trap)
        # Trap Nation
        play_stream "6Qq2OMFh8Pc"
        ;;
esac
