#!/usr/bin/env bash

# Stop execution if an error occurs
set -e

distro=$(cat /etc/os-release | grep -oP '(?<=^ID=).*')
# echo "Detected distribution: $distro"

case $distro in
    # Ubuntu / Debian
    ubuntu|debian|pop)
        if `command -v nala > /dev/null`; then
            sudo nala upgrade
        else
            sudo apt-get update
            sudo apt-get dist-upgrade
        fi
        ;;

    arch)

        if which paru >/dev/null 2>&1; then
            # echo 'Update using paru'
            prog='paru'

        elif which yay >/dev/null 2>&1; then
            # echo 'Update using yay'
            prog='yay'

        else
            # echo 'Update using pacman'
            prog='sudo pacman'
        fi

        $prog -Syu --noconfirm
        ;;

    nixos)
        # Path to the folder containing `flake.nix`
        nix_dir=$HOME/config

        # Update the flake's inputs
        nix flake update $nix_dir -L

        # Reload the system configuration
        case $1 in
            cuda)
                nixos-rebuild switch \
                    --fast \
                    --flake $nix_dir\#cuda \
                    --target-host root@cuda \
                    --build-host root@cuda
                ;;
            `hostname`|"")
                sudo nixos-rebuild switch --flake $nix_dir -v

                # Clean the store (garbage collection)
                # Also removes old generations
                sudo nix-collect-garbage --delete-older-than 2d
                ;;
        esac
        ;;
esac
