#!/bin/sh

profile=$1

flake_dir="$HOME/config"

rm -f $flake_dir/flake.lock

git -C $flake_dir pull

nix flake update $flake_dir

rm $HOME/.config/user-dirs.dirs
home-manager switch --flake $flake_dir\#$profile -v

nix-collect-garbage --delete-older-than 2d
