#!/bin/bash

DEFAULT_VAL=500

function set_vibrance {
    VIBRANCE_VALUE=$1
    nvidia-settings -a "DigitalVibrance=$VIBRANCE_VALUE" > /dev/null
}

function disable_vibrance {
    set_vibrance 0
}

function enable_vibrance {
    set_vibrance $DEFAULT_VAL
}

function toggle_vibrance {
    if [[ $(nvidia-settings -q "DigitalVibrance" | grep "Attribute.* 0\.") ]]
    then
        enable_vibrance
        echo "Vibrance Enabled"
    else
        disable_vibrance
        echo "Vibrance Disabled"
    fi
}

case $1 in
    toggle)
        toggle_vibrance
        ;;
    enable)
        enable_vibrance
        ;;
    disable)
        disable_vibrance
        ;;
    '^[0-9]+$')
        # TODO case where an integer value is given
        # --> not working yet
        set_vibrance $1
        ;;
    *)
        toggle_vibrance
esac
