#!/bin/sh

SOFTWARE_DIR=/scratch/alya/galepage/software

set -e

# alias apt_install="sudo apt install -y --no-install-recommends"
alias apt_install="sudo nala install -y --no-install-recommends"


# Update the system
sudo apt update && sudo apt upgrade

echo "deb http://deb.volian.org/volian/ scar main" | sudo tee /etc/apt/sources.list.d/volian-archive-scar-unstable.list
wget -qO - https://deb.volian.org/volian/scar.key | sudo tee /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg > /dev/null
sudo apt update
sudo apt install -y nala


# Shell & CLI tools
apt_install bat
apt_install exa
apt_install ranger
apt_install ripgrep
apt_install zsh

apt_install tmux
apt_install pavucontrol

apt_install python3 python3-pip python3-venv python3-distutils
apt_install nvidia-cuda-toolkit

apt_install htop btop nvtop
apt_install pipx && pipx install nvitop


# Go
sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt update
apt_install golang


##########
# Neovim #
##########

# Install dependencies
apt_install \
    ninja-build \
    gettext \
    libtool \
    libtool-bin \
    autoconf \
    automake \
    cmake \
    g++ \
    pkg-config \
    unzip \
    curl \
    doxygen

# Clone the repo if needed
cd $SOFTWARE_DIR/
# If the folder doesn't exist, clone the repo and build
if ! [ -d neovim ]; then
    git clone https://github.com/neovim/neovim
fi
cd neovim
make clean && rm -rf build
make CMAKE_BUILD_TYPE=RelWithDebInfo -j `nproc`
sudo make install

sudo bash -c "$(curl -fsSL https://git.io/JsADh || wget -q https://git.io/JsADh -O -)"


cd $SOFTWARE_DIR/
# If the folder doesn't exist, clone the repo and build
if ! [ -d lazygit ]; then
    git clone https://github.com/jesseduffield/lazygit.git
fi
cd lazygit
go install
ln -s $GOPATH/bin/lazygit $HOME/.local/bin/


cd $SOFTWARE_DIR/
# If the folder doesn't exist, clone the repo and build
if ! [ -d pfetch ]; then
    git clone https://github.com/dylanaraps/pfetch.git
fi
cd pfetch
sudo make install
