#!/bin/sh

create_session () {

    COMMAND='cd /scratch/alya/galepage/.remi_projects/rlan && exec zsh --init-file <(echo " conda activate rlenv ")'
    COMMAND='cd /scratch/alya/galepage/.remi_projects/rlan && bash'
    COMMAND='sleep 10 && ls'
    echo $COMMAND

    DIRECTORY='/scratch/alya/galepage/.remi_projects/rlan'

    # tmux new-session -s 'rlan' -c $DIRECTORY $COMMAND
    tmux new-session -s 'rlan' -c $DIRECTORY

}

tmux attach-session -t 'rlan' > /dev/null 2>&1 || create_session
