name: Flake CI

on:
  pull_request:
    paths:
      - "flake.nix"
      - "flake.lock"

permissions:
  contents: read

jobs:
  nix-check:
    name: nix-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: nix flake check
        run: nix flake check --print-build-logs --no-update-lock-file
